language: python
python: 3.9
dist: focal
services:
    - mysql
install:
    - pip install -r requirements.txt
    - pip install mysqlclient
script:
    - python manage.py collectstatic
    - python manage.py test
