language: python
python: 3.9
install:
    - sudo apt-get install postgresql-12
    - pip install -r requirements.txt
before script:
    - sudo service postgresql start
script:
    - python manage.py collectstatic
    - python manage.py test
