# Generated by Django 3.0.6 on 2020-06-10 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200610_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopantry',
            name='bestbefore',
        ),
        migrations.AddField(
            model_name='usertopantry',
            name='frozen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertopantry',
            name='opened',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertopantry',
            name='usebefore',
            field=models.DateTimeField(blank=True),
        ),
    ]
