# Generated by Django 3.0.6 on 2020-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200610_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopantry',
            name='frozen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertopantry',
            name='opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertopantry',
            name='usebefore',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
