# Generated by Django 3.0.6 on 2020-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingredients_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='meta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
