# Generated by Django 3.0.6 on 2020-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipeinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='wine_pairing',
            field=models.TextField(blank=True),
        ),
    ]
