# Generated by Django 3.0.7 on 2020-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_myrecipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecipe',
            name='image',
            field=models.CharField(choices=[('salad.png', 'salad.png'), ('pizza.png', 'pizza.png'), ('pancake.png', 'pancake.png'), ('cake2.png', 'cake2.png'), ('hamburger.png', 'hamburger.png'), ('rib.png', 'rib.png')], default='salad.png', max_length=64),
        ),
    ]
