# Generated by Django 3.0.7 on 2020-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20200618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecipeingredients',
            name='unit',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
