# Generated by Django 3.0.7 on 2020-06-19 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20200618_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertorecipe',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
